### ISSUE TITLE
Decide on statistics to calculate

### ISSUE THREAD

**Issue by thxo** [smin99/fishery_wifi#7]

**Comment by thxo** [comment]
**Shiny app**
Sidebar selectors: state, city
Data panel: big map, table, statistics

By default, the big map is a **national-level (continental US) heatmap**. We do quantitative shading for each state depending on the median Internet download speed.

After a **state** is selected an additional **pie chart** is shown. It depicts a pie chart of logarithm categories of Internet speeds (0-1 Mbps, 1-10Mbps, 10-100Mbps).

After you select a state, the **city** drop-down list, and you can select a city. After you select a city, a **table** that contains all the ISPs and their respective UL/DL speeds appears.

Also, when we select a state, we show:
- 75%ile internet speed.
- 25%ile internet speed.
- median internet speed.
- standard deviation (to show if there is large inequality). 

Sounds good?

**Comment by ktw0222** [comment]
Should I make the heat map also reflect the 25% and 75%?
